---
- hosts: servers
  serial: 1
  tasks:

  - name: Ensure directory exists
    file:
      path: /tmp/test2
      state: directory

  - name: Template a file to another place
    template:
      src: roy_hostname.j2
      dest: /tmp/test2/hostname.conf

